# Generated by Django 4.2.3 on 2023-07-21 05:16

from django.db import migrations, models
import organization_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='logo',
            field=models.ImageField(upload_to=organization_app.models.society_file),
        ),
    ]
