# Generated by Django 4.2.3 on 2023-07-21 05:28

from django.db import migrations, models
import organization_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0002_alter_society_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(upload_to=organization_app.models.institute_file),
        ),
        migrations.AlterField(
            model_name='officebearerss',
            name='photo',
            field=models.ImageField(upload_to=organization_app.models.office_file),
        ),
    ]
